# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-27 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('login', models.CharField(max_length=32, unique=True, verbose_name='Login')),
                ('first_name', models.CharField(max_length=32, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=32, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone')),
                ('days', multiselectfield.db.fields.MultiSelectField(choices=[(b'1', 'Monday'), (b'2', 'Tuesday'), (b'3', 'Wednesday'), (b'4', 'Thursday'), (b'5', 'Friday'), (b'6', 'Saturday'), (b'7', 'Sunday')], default=[b'1', b'2', b'3', b'4', b'5'], max_length=13)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='title')),
                ('body', models.TextField(blank=True, max_length=1000, null=True, verbose_name='body')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[(b'NOT_AVAILABLE', b'not available'), (b'AVAILABLE', b'available'), (b'REMOTE', b'remote'), (b'DAY_OFF', b'day_off')], default=b'NOT_AVAILABLE', max_length=13, verbose_name='status')),
                ('admin_comment', models.TextField(blank=True, max_length=1000, null=True, verbose_name='admin comment')),
                ('accepted', models.CharField(choices=[(b'0', b'not_decided'), (b'1', b'Accepted'), (b'2', b'Rejected')], default=b'0', max_length=1, verbose_name='accepted')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Creator', to='djchecker.CustomUser', verbose_name='creator')),
                ('decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Decision', to='djchecker.CustomUser', verbose_name='decision by')),
            ],
            options={
                'verbose_name_plural': ('entries',),
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150, unique=True, verbose_name='label')),
                ('fa_icon', models.CharField(blank=True, max_length=150, null=True, verbose_name='fontawsome icon')),
                ('color', models.CharField(choices=[(b'RED', b'red'), (b'BLUE', b'blue'), (b'ORANGE', b'orange'), (b'GREEN', b'green'), (b'YELLOW', b'yellow'), (b'WHITE', b'white')], default=b'RED', max_length=13, verbose_name='color')),
                ('for_all_users', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'event type',
                'verbose_name_plural': 'event types',
            },
        ),
        migrations.CreateModel(
            name='HTMLStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[(b'pl', b'Polish'), (b'en', b'English'), (b'de', b'German')], default=b'pl', max_length=2)),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djchecker.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, max_length=1000, null=True, verbose_name='body')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField()),
                ('comment', models.TextField(blank=True, max_length=1000, null=True, verbose_name='comment')),
                ('note_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_author', to='djchecker.CustomUser', verbose_name='note_author')),
            ],
            options={
                'verbose_name_plural': ('notes',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='djchecker.CustomUser')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ThemeSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[(b'1', b'normal'), (b'2', b'dark')], default=b'1', max_length=1)),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djchecker.CustomUser')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djchecker.EventType'),
        ),
    ]
